services:
  observatory:
    image: "ghcr.io/beingflo/observatory:0.1.25"
    container_name: observatory
    env_file: ".env.prod"
    volumes:
      - /home/florian/observatory/db:/usr/src/app/db/
    restart: unless-stopped
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
