name: Build

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build . --tag observatory
      - name: Tag image
        run: docker tag observatory:latest ghcr.io/${{ github.actor }}/observatory:latest
      - name: Push image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.actor }}/observatory:latest
